##
# ScandiPWA_ContactGraphQl
#
# @category    ScandiPWA
# @package     ScandiPWA_ContactGraphQl
# @copyright   Copyright © Scandiweb, Inc. All rights reserved.
# @copyright   Modifications © Selveq. All rights reserved.
# @license     OSL-3.0 (Open Software License ("OSL") v. 3.0)
# See LICENSE for license details.
##

type Query {
    contactPageConfig: ContactPageConfig @resolver(class: "ScandiPWA\\ContactGraphQl\\Model\\Resolver\\ContactPageConfig") @doc(description: "Contact Us page config") @cache(cacheIdentity: "ScandiPWA\\ContactGraphQl\\Model\\Resolver\\ContactPageConfig\\Identity")
}

type Mutation {
    contactForm(contact: ContactForm!): ContactFormResponse @resolver(class: "ScandiPWA\\ContactGraphQl\\Model\\Resolver\\Contact") @doc(description: "Send contact form")
}

input ContactForm {
    name: String
    telephone: String
    email: String
    message: String
}

type ContactFormResponse {
    message: String
}

type ContactPageConfig {
    enabled: Boolean
}
